name: ihsana
description: "Smart MoCA Diagnostic System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2


  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0

  # API & Networking
  http: ^1.1.0
  http_parser: ^4.0.2

  # Files & Paths
  path_provider: ^2.1.1
  path: ^1.8.3

  open_filex: ^4.3.2

  # Permissions & Media
  permission_handler: ^11.0.1
  image_picker: ^1.0.7
  audioplayers: ^5.2.1
  flutter_sound: ^9.15.0

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/fonts/
    - assets/images/
    - assets/audio/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
